title = 'rodstewart.io'
baseURL = 'https://lab.rodstewart.io/'
languageCode = 'en-us'
# theme = 'diary'
# theme = ["github.com/amazingrise/hugo-theme-diary"]
theme = ["github.com/theNewDynamic/gohugo-theme-ananke/v2"]
